# Generated by Django 3.2.4 on 2021-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='smaller_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='smaller-product-thumbnails'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product-thumbnails'),
        ),
    ]
