# Generated by Django 3.2.4 on 2021-06-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210619_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='smaller_thumbnail',
        ),
    ]
